# database init, supports mysql too
# database: h2
# database: mysql

# Logging
logging:
  level:
    org.springframework: INFO
#    org.springframework.web: DEBUG
#    org.springframework.context.annotation: TRACE

# Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'

# Active Spring profiles
spring:
  profiles:
    active: production
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  datasource:
#    initialization-mode: always
#    data: classpath*:db/${database}/data.sql
#    schema: classpath*:db/${database}/schema.sql
#    data: classpath*:h2/data.sql
#    schema: classpath*:h2/schema.sql
    url: 'jdbc:h2:~/test'
    username: sa
    password: 
  jpa:
    generate-ddl: true
    show-sql: true
  messages:
    basename: messages
  thymeleaf:
    mode: HTML
  song: 
    top-music-directory: 'C:\music'